export const SET_POSTS = 'SET_POSTS';
export const REMOVE_POSTS = 'REMOVE_POSTS';
export const TOTAL_CALC = 'TOTAL_CALC';
export const FETCH_ALL_CARD = 'FETCH_ALL_CARD';
export const FETCH_ALL_CARD_SUCCESS = 'FETCH_ALL_CARD_SUCCESS';
export const FETCH_ALL_CARD_ERROR = 'FETCH_ALL_CARD_ERROR';
export const FETCH_TYPES = 'FETCH_TYPES';
export const FETCH_SUBTYPES = 'FETCH_SUBTYPES';